sign_in_button = "xpath=//a[@class = 'login']"
create_account_field_registration_page = "xpath=//input[@name='email_create']"
create_account_button_registration_page = "xpath=//*[@id='SubmitCreate']"
customer_firstname_registration_page = "xpath=//*[@id='customer_firstname']"
customer_lastname_registration_page = "xpath=//*[@id='customer_lastname']"
email_registration_page = "xpath=//*[@id='email']"
password_registration_page = "xpath=//*[@id='passwd']"
firstname_registration_page = "xpath=//*[@id='firstname']"
lastname_registration_page = "xpath=//*[@id='lastname']"
address_registration_page = "xpath=//*[@id='address1']"
city_registration_page = "xpath=//*[@id='city']"
state_registration_page = "xpath=//*[@id='id_state']"
zip_registration_page = "xpath=//*[@id='postcode']"
country_registration_page = "xpath=//*[@id='id_country']"
phone_mobile_registration_page = "xpath=//*[@id='phone_mobile']"
alias_registration_page = "xpath=//*[@id='alias']"
register_button_registration_page = "xpath=//*[@id='submitAccount']"

